import { Printer, Save } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase, supabaseReady } from '../../lib/supabase'
import { useGymStore } from '../../store/useGymStore'

const GOAL_LABELS = { weight_loss: 'Weight Loss', muscle_gain: 'Muscle Gain', maintenance: 'Maintenance' }
const DIET_LABELS  = { veg: 'Vegetarian', non_veg: 'Non-Veg', vegan: 'Vegan' }

export default function MealPlanDisplay({ plan, onSaved }) {
  const activeGymId = useGymStore((s) => s.activeGymId)
  if (!plan) return null

  async function handleSave() {
    if (!supabaseReady || !plan.memberId) { toast.error('No member selected'); return }
    const { error } = await supabase.from('diet_plans').insert({
      gym_id:    activeGymId,
      member_id: plan.memberId,
      goal:      plan.goal,
      diet_type: plan.dietType,
      calories:  plan.calories,
      plan_json: plan,
    })
    if (error) toast.error('Could not save plan')
    else { toast.success('Plan saved'); onSaved?.() }
  }

  return (
    <div>
      {/* Toolbar */}
      <div className="flex items-center justify-between mb-4 no-print">
        <div>
          <p className="text-sm font-semibold text-gray-800">{plan.name}</p>
          {plan.memberName && (
            <p className="text-xs text-gray-400">For {plan.memberName}</p>
          )}
        </div>
        <div className="flex gap-2">
          {plan.memberId && (
            <button onClick={handleSave} className="btn-secondary flex items-center gap-1.5 text-xs py-1.5">
              <Save size={13} /> Save
            </button>
          )}
          <button onClick={() => window.print()} className="btn-secondary flex items-center gap-1.5 text-xs py-1.5">
            <Printer size={13} /> Print / PDF
          </button>
        </div>
      </div>

      {/* Print header — only visible in print */}
      <div className="print-only hidden mb-6">
        <h1 className="text-xl font-bold">{plan.name}</h1>
        {plan.memberName && <p className="text-sm text-gray-600">Member: {plan.memberName}</p>}
        <p className="text-sm text-gray-600">Generated by FitBook</p>
      </div>

      {/* Summary row */}
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 mb-4">
        <SumCard label="Total calories" value={`${plan.calories} kcal`} color="text-primary-dark" bg="bg-primary-light" />
        <SumCard label="Protein"        value={`${plan.macros.protein} g`} color="text-success-dark" bg="bg-success-light" />
        <SumCard label="Carbohydrates"  value={`${plan.macros.carbs} g`} color="text-warning-dark" bg="bg-warning-light" />
        <SumCard label="Fat"            value={`${plan.macros.fat} g`} color="text-orange-700" bg="bg-orange-50" />
      </div>

      {/* Tags */}
      <div className="flex gap-2 mb-5 flex-wrap">
        <span className="badge-purple">{GOAL_LABELS[plan.goal] || plan.goal}</span>
        <span className="badge-green">{DIET_LABELS[plan.dietType] || plan.dietType}</span>
      </div>

      {/* Meals */}
      <div className="space-y-3">
        {plan.meals.map((meal, i) => (
          <div key={i} className="meal-card bg-gray-50 rounded-card p-4">
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs font-semibold text-gray-700">{meal.time}</p>
              <span className="text-[10px] bg-white border border-gray-200 text-gray-500 px-2 py-0.5 rounded-full">
                ~{meal.calories} kcal
              </span>
            </div>
            <ul className="space-y-1">
              {meal.items.map((item, j) => (
                <li key={j} className="flex items-start gap-2 text-sm text-gray-700">
                  <span className="text-primary mt-0.5">•</span>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {/* Tips */}
      {plan.tips?.length > 0 && (
        <div className="mt-5 bg-amber-50 border border-amber-100 rounded-card p-4">
          <p className="text-xs font-semibold text-amber-800 mb-2">Lifestyle tips</p>
          <ul className="space-y-1">
            {plan.tips.map((tip, i) => (
              <li key={i} className="text-xs text-amber-700 flex items-start gap-2">
                <span className="mt-0.5">✓</span>{tip}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

function SumCard({ label, value, color, bg }) {
  return (
    <div className={`${bg} rounded-btn p-3`}>
      <p className="text-[10px] text-gray-500 mb-0.5">{label}</p>
      <p className={`text-sm font-bold ${color}`}>{value}</p>
    </div>
  )
}
